// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// sk9822_lane //
// ----------- //

#define sk9822_lane_wrap_target 0
#define sk9822_lane_wrap 3
#define sk9822_lane_pio_version 0

static const uint16_t sk9822_lane_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0xe027, //  1: set    x, 7            side 0
    0x6001, //  2: out    pins, 1         side 0
    0x1042, //  3: jmp    x--, 2          side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sk9822_lane_program = {
    .instructions = sk9822_lane_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = sk9822_lane_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sk9822_lane_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sk9822_lane_wrap_target, offset + sk9822_lane_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

