// firmware/blade/src/sk9822_pio.c
// SYNCHRON Blade Controller — SK9822 PIO driver
//
// Instantiates 4 PIO state machines (one per segment lane).
// All 4 SMs run the same program and are started simultaneously
// so their clocks are synchronised — all DATA lines change at
// exactly the same time relative to their respective CLK lines.
//
// GPIO layout (from HW_PINS_BLADE.md):
//   Lane 0: GP2 (DATA), GP3 (CLK)  → Seg1 Top
//   Lane 1: GP4 (DATA), GP5 (CLK)  → Seg2 Top
//   Lane 2: GP12 (DATA), GP13 (CLK)→ Seg1 Bot
//   Lane 3: GP11 (DATA), GP15 (CLK)→ Seg2 Bot
//
// Usage:
//   sk9822_pio_init();                    // call once at boot
//   sk9822_pio_write_segment(lane, buf, n_pixels);  // call per slice
//   sk9822_pio_latch();                   // call after all 4 lanes written

#include "sk9822_pio.h"
#include "hardware/pio.h"
#include "hardware/structs/pio.h"
#include "hardware/dma.h"
#include "hardware/clocks.h"
#include "pico/stdlib.h"
#include "sk9822_parallel.pio.h"   // generated by pioasm from .pio file
#include <string.h>
#include <stdio.h>

// ─── Lane definitions ────────────────────────────────────────────────────────

#define NUM_LANES       4
#define PIXELS_PER_SEG  36
#define BYTES_PER_PIX   4    // SK9822: [0xE0|bri][B][G][R]

// Target SPI clock: 10MHz
// sys_clk = 125MHz, 2 cycles per bit → clkdiv = 125/(2*10) = 6.25
#define SPI_MHZ         10.0f
#define PIO_CLKDIV      (clock_get_hz(clk_sys) / (2.0f * SPI_MHZ * 1e6f))

typedef struct {
    uint    data_gpio;
    uint    clk_gpio;
    PIO     pio;
    uint    sm;
    int     dma_chan;
} Lane;

static Lane lanes[NUM_LANES] = {
    { .data_gpio =  2, .clk_gpio =  3, .pio = pio0 },  // Seg1 Top
    { .data_gpio =  4, .clk_gpio =  5, .pio = pio0 },  // Seg2 Top
    { .data_gpio = 12, .clk_gpio = 13, .pio = pio1 },  // Seg1 Bot
    { .data_gpio = 11, .clk_gpio = 15, .pio = pio1 },  // Seg2 Bot
};

// TX buffers: one per lane — start frame + pixel data + end frame
// Start frame: 4 bytes of 0x00
// 36 pixels × 4 bytes = 144 bytes
// End frame: ceil(36/16) = 3 bytes of 0xFF
// Total: 4 + 144 + 3 = 151 bytes, padded to 152 (word-aligned)
#define FRAME_BYTES     (4 + PIXELS_PER_SEG * BYTES_PER_PIX + 4)
static uint8_t lane_buf[NUM_LANES][FRAME_BYTES];

// DMA channel for each lane
static int dma_chan[NUM_LANES];

// ─── PIO initialisation ───────────────────────────────────────────────────────

static uint pio_program_offset_pio0;
static uint pio_program_offset_pio1;

void sk9822_pio_init(void) {
    // Load program into both PIO blocks
    // pio0 handles lanes 0+1, pio1 handles lanes 2+3
    pio_program_offset_pio0 = pio_add_program(pio0, &sk9822_lane_program);
    pio_program_offset_pio1 = pio_add_program(pio1, &sk9822_lane_program);

    for (int i = 0; i < NUM_LANES; i++) {
        PIO pio = lanes[i].pio;
        uint offset = (pio == pio0) ? pio_program_offset_pio0 : pio_program_offset_pio1;

        // Claim a state machine
        int sm = pio_claim_unused_sm(pio, true);
        lanes[i].sm = (uint)sm;

        // Configure SM
        pio_sm_config c = sk9822_lane_program_get_default_config(offset);

        // OUT pin = DATA gpio (1 pin, shift left/MSB first)
        sm_config_set_out_pins(&c, lanes[i].data_gpio, 1);

        // SIDE SET pin = CLK gpio
        sm_config_set_sideset_pins(&c, lanes[i].clk_gpio);

        // Shift direction: left (MSB first), autopull at 8 bits
        // We push one byte per FIFO word (8 bits used, rest don't care)
        // Actually: push 32-bit words, SM shifts out 8 bits then wraps
        sm_config_set_out_shift(&c, false, true, 8); // shift left, autopull, threshold=8

        // Clock divider for 10MHz SPI
        float clkdiv = (float)clock_get_hz(clk_sys) / (2.0f * SPI_MHZ * 1000000.0f);
        sm_config_set_clkdiv(&c, clkdiv);

        // Init GPIOs
        pio_gpio_init(pio, lanes[i].data_gpio);
        pio_gpio_init(pio, lanes[i].clk_gpio);
        pio_sm_set_consecutive_pindirs(pio, sm, lanes[i].data_gpio, 1, true); // DATA out
        pio_sm_set_consecutive_pindirs(pio, sm, lanes[i].clk_gpio,  1, true); // CLK out

        // Load config — do NOT enable yet (start all together)
        pio_sm_init(pio, sm, offset, &c);

        // Claim DMA channel
        dma_chan[i] = dma_claim_unused_channel(true);
        lanes[i].dma_chan = dma_chan[i];

        printf("[sk9822] lane %d: DATA=GP%d CLK=GP%d PIO%d SM%d DMA%d\n",
               i, lanes[i].data_gpio, lanes[i].clk_gpio,
               (pio == pio0) ? 0 : 1, sm, dma_chan[i]);
    }

    // Start all 4 SMs simultaneously using SM enable mask
    // This ensures their clocks are phase-aligned from the first cycle
    pio_enable_sm_mask_in_sync(pio0, 
        (1u << lanes[0].sm) | (1u << lanes[1].sm));
    pio_enable_sm_mask_in_sync(pio1, 
        (1u << lanes[2].sm) | (1u << lanes[3].sm));

    printf("[sk9822] PIO init complete. 4 lanes active at %.1f MHz\n", SPI_MHZ);
}

// ─── Frame assembly ───────────────────────────────────────────────────────────

// Build a complete SK9822 frame for one segment into lane_buf[lane]
// pixel_data: pointer to PIXELS_PER_SEG × 4 bytes of [0xE0|bri, B, G, R]
static void build_frame(int lane, const uint8_t *pixel_data) {
    uint8_t *buf = lane_buf[lane];
    int off = 0;

    // Start frame: 4 × 0x00
    buf[off++] = 0x00;
    buf[off++] = 0x00;
    buf[off++] = 0x00;
    buf[off++] = 0x00;

    // Pixel data (already in [0xE0|bri, B, G, R] format)
    memcpy(buf + off, pixel_data, PIXELS_PER_SEG * BYTES_PER_PIX);
    off += PIXELS_PER_SEG * BYTES_PER_PIX;

    // End frame: ceil(36/16) = 3 bytes of 0xFF
    buf[off++] = 0xFF;
    buf[off++] = 0xFF;
    buf[off++] = 0xFF;
}

// ─── DMA transfer ────────────────────────────────────────────────────────────

// Kick DMA transfer for one lane — non-blocking, runs in background
static void dma_kick(int lane) {
    dma_channel_config cfg = dma_channel_get_default_config(dma_chan[lane]);
    channel_config_set_transfer_data_size(&cfg, DMA_SIZE_8);
    channel_config_set_read_increment(&cfg, true);
    channel_config_set_write_increment(&cfg, false);

    // DREQ: wait for PIO TX FIFO to have space
    PIO pio = lanes[lane].pio;
    uint sm  = lanes[lane].sm;
    channel_config_set_dreq(&cfg, pio_get_dreq(pio, sm, true));

    dma_channel_configure(
        dma_chan[lane],
        &cfg,
        &pio->txf[sm],               // write to PIO TX FIFO
        lane_buf[lane],              // read from frame buffer
        FRAME_BYTES,                 // transfer FRAME_BYTES bytes
        true                         // start immediately
    );
}

// ─── Public API ───────────────────────────────────────────────────────────────

// Write one segment's pixel data to a lane.
// pixel_data: PIXELS_PER_SEG × 4 bytes in [0xE0|bri, B, G, R] order
// Kicks DMA — returns before transfer completes.
void sk9822_pio_write_lane(int lane, const uint8_t *pixel_data) {
    if (lane < 0 || lane >= NUM_LANES) return;
    build_frame(lane, pixel_data);
    dma_kick(lane);
}

// Write all 4 lanes simultaneously from a full slice buffer.
// slice_buf: PIXELS_PER_SEG * NUM_LANES * BYTES_PER_PIX bytes
// Layout: [seg1_top: 36px][seg2_top: 36px][seg1_bot: 36px][seg2_bot: 36px]
void sk9822_pio_write_slice(const uint8_t *slice_buf) {
    for (int i = 0; i < NUM_LANES; i++) {
        build_frame(i, slice_buf + i * PIXELS_PER_SEG * BYTES_PER_PIX);
        dma_kick(i);
    }
}

// Wait for all 4 DMA transfers to complete.
// Call this before fire_slice() returns to ensure LEDs have latched.
// In practice: at 10MHz, 151 bytes takes ~121µs — well within slice window.
void sk9822_pio_wait(void) {
    for (int i = 0; i < NUM_LANES; i++) {
        dma_channel_wait_for_finish_blocking(dma_chan[i]);
    }
}

// Check if all transfers are complete without blocking.
// Returns true if all 4 lanes are idle.
bool sk9822_pio_done(void) {
    for (int i = 0; i < NUM_LANES; i++) {
        if (dma_channel_is_busy(dma_chan[i])) return false;
    }
    return true;
}
