if(DEFINED ENV{PICO_SDK_PATH})
  set(PICO_SDK_PATH $ENV{PICO_SDK_PATH})
endif()
if(NOT PICO_SDK_PATH)
  message(FATAL_ERROR "PICO_SDK_PATH not set. Clone pico-sdk and set env var.")
endif()
include(${PICO_SDK_PATH}/external/pico_sdk_import.cmake)
